### ISSUE TITLE
Not working when bundle:false

### ISSUE THREAD

**Issue by fschwalm** [kazijawad/esbuild-plugin-svgr#3]
Hello!
Should this plugin work with the option bundle:false?

Thank you so much!

**Comment by kazijawad** [comment]
Yes, the plugin should work fine with `bundle: false`.

**Comment by fschwalm** [comment]
Ok, i will create a demo repo with the problem.

Thx

**Comment by fschwalm** [comment]
I created a repo to reproduce the error.


https://github.com/fschwalm/esbuild-svgr-issue

Working scenario
```
1- Clone the repo
2- yarn && yarn start:with-bundle 
3- Open http://localhost:3000
It will works!
```

Not Working scenario
```
just change step 2:
yarn start:without-bundle
```

When use bundle:false, in the build folder it keep the following import:
```
import { default as default2 } from "./arrow-right.svg";
```
and not include the file.

I've tried include svg's in my globby pattern:

```
esbuild.ts line 14
path.resolve(rootPath, "src/**/*.svg"),
```
Then it loads the svg file and transpiles to js with plugin, but the reference in the index.js keep the import to svg file.

Any help are welcome!

Thank you so much!

**Comment by kazijawad** [comment]
Thanks for the example! I'll take a look and see if I can update the plugin to handle non-bundled projects.

**Comment by fschwalm** [comment]
Ok thank you so much!

I'm not using `bundle:true` because _tree-shaking_.

**Comment by kazijawad** [comment]
So this plugin relies on bundling to work properly because the `onLoad` and `onResolve` methods used to resolve the imports don't get fired when the bundling is set to `false`. It appears this is a general situation with esbuild and you would need to copy over the assets depending on your project setup. Here is a reference implementation that you might find helpful: https://github.com/evanw/esbuild/issues/982#issuecomment-802452408
